### ISSUE TITLE
upload of zipped csv file fails

### ISSUE THREAD

**Issue by brynk** [AtlasOfLivingAustralia/sandbox#16]
Grails Runtime Exception
Error Details
Error 500: Executing action [uploadFile] of controller [au.org.ala.datacheck.UploadController] caused exception: Runtime error executing action
Servlet: grails
URI: /datacheck/grails/upload/uploadFile.dispatch
Exception Message: Unable to create directory /data/datacheck/uploads/1426906722486
Caused by: Unable to create directory /data/datacheck/uploads/1426906722486
Class: UploadController
At Line: [46]
Code Snippet:
Stack Trace

java.io.IOException: Unable to create directory /data/datacheck/uploads/1426906722486

	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2211)

	at au.org.ala.datacheck.UploadController.uploadFile(UploadController.groovy:46)

	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)

	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)

	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)

	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

	at java.lang.Thread.run(Thread.java:744)

**Comment by brynk** [comment]
disc full, working
